  - job_name: 'blackbox_dns'
    scrape_interval: 30s
    metrics_path: /probe
    static_configs:
     - targets:
         - mlp.com_a:8.8.8.8
         - mlp.com_mx:8.8.8.8
         - mlp.com_www:8.8.8.8
         - mlp.com_ftp:8.8.8.8
         - mlp.com_athome:8.8.8.8
         - mlp.com_mail:8.8.8.8
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - source_labels: [__param_target]
        regex: '(.*):.*$'
        replacement: '$1'
        target_label: 'domain'
      - source_labels: [__param_target]
        regex: '.*:(.*)$'
        replacement: '$1'
        target_label: 'instance'
      - source_labels: [__param_target]
        regex: '(.*):.*$'
        replacement: '$1'
        target_label: __param_module
      - source_labels: [__param_target]
        regex: '.*:(.*)$'
        replacement: '$1'
        target_label: __param_target
      - target_label: __address__
        replacement: 127.0.0.1:9115  # The blackbox exporter's real hostname:port.
